### ISSUE TITLE
IRB application

### ISSUE THREAD

**Issue by LeahRosenzweig** [gsbDBI/facebook_adaptive#1]
The next deadline for Stanford IRB application is 7/1 (5pm PT) for review during the 7/31 meeting. 

Here is a quick checklist of what we'll need for the application:

- [x] 1. IRB certificates

- [x] 2. Description of recruitment -- decide how much we're paying respondents ([link](https://docs.google.com/spreadsheets/d/1-lv6Lr67tSr6Ffj1x8prFrjzcDzGOwQ-K3A0Gab-dgc/edit?usp=sharing) to draft budget), target protocol for FB ads

- [x] 3. Experimental design -- treatments

- [x] 4. Survey instrument

submit forms here: https://eprotocol.stanford.edu/ : IRB-57430

**Comment by mollyow** [comment]
Thanks for getting this started @LeahRosenzweig!

Running questions (based on conversations with Leah):

- **Survey delivery: Qualtrics survey or chatbot?** 
  + The chatbot is potentially more engaging, keeps respondents in the Facebook universe, and allows us to ping respondents to keep them engaged if they stop responding to the survey. 
  + However, Qualtrics is much more developed for different types of survey questions and enforcing response choices/types of data entry. The chatbot data may require more cleaning and setting up the chatbot requires more work to ensure the bot is robust to people engaging with it in different ways. 
  + Qualtrics may also be preferable for delivery of some treatments, TBD. 

Proposal: preference for chatbot, but this will likely depend on final decisions regarding treatment delivery and outcome measurement. 

- **Geographic targeting: Which countr(y/ies)?** Nigeria/Kenya/South Africa have large monthly Facebook user populations (27 / 21 / 8.8 million respectively). If targeting multiple countries
  + This will be somewhat more challenging logistically, 
  + Sample likely to vary across countries (maybe not a problem here)
  + Interesting substantively for cross country-comparison. 
  + In South Africa, we can't do mobile money for incentivizing in the same way. 

Proposal: focus just on Nigeria and Kenya. 


- **Language: Translate to local languages?** 

Proposal: conduct all surveys in English; this won't be nationally representative, but should cover large populations across all potential target areas

**Comment by mollyow** [comment]
Working plan, based on 6/26 call:

- **Stimuli** Focusing on COVID-19 related headlines that can be refuted by [WHO myth busters](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public/myth-busters); specifically, with respect to hoax cures or false transmission/prevention techniques. These stimuli will consequently *not* be representative of the wide range of types of misinformation that spread online, or even health-related misinformation. Consequently, interventions that are effective and curbing spread of this type of misinformation may not be effective for, e.g., political misinformation. However, this study will be relevant to a current and pressing public health crisis where fake cures can inflict serious personal harm; the study design and can provide a structure for learning the most effective context-aware interventions for different types of stimuli. 
Assigned: Leah, may pass on to Raymond if we need more collected
To do: 
  - [ ] Comb through existing set of stimuli used for Leah's previous Nigeria study, add stimuli for Kenya. Google spreadsheet to be linked. 
  - [ ] Eventually, mock-up images as if shared on a Facebook page. 


- **Demographics** Modified from Leah's existing Nigeria study. 
Assigned: Leah
To do: 
  - [ ] Plug into the working [draft script](https://docs.google.com/spreadsheets/d/1hhWv_ZxVJA1xcfnK3URFWjN4awJjL1DvSc1HcSW9-sk/edit#gid=89947233).    
  - [ ] Potentially add further questions on frequency and type of news consumption. 
  - [ ] Also add any attention checks where relevant. 


- **Treatments** Proposed treatments linked [here]
(https://docs.google.com/spreadsheets/d/1hhWv_ZxVJA1xcfnK3URFWjN4awJjL1DvSc1HcSW9-sk/edit#gid=2041667001); 
Assigned: Molly
To do: 
  - [ ] Further refine and plug into the working [draft script](https://docs.google.com/spreadsheets/d/1hhWv_ZxVJA1xcfnK3URFWjN4awJjL1DvSc1HcSW9-sk/edit#gid=89947233)  
  - [ ] Mock up images for headline-level treatments once stimuli are finalized. 


- **Outcomes** Proposed outcomes linked [here](https://docs.google.com/spreadsheets/d/1hhWv_ZxVJA1xcfnK3URFWjN4awJjL1DvSc1HcSW9-sk/edit#gid=1254237704). Outcomes will primarily focus on propensity to *share* misinformation, and will be combined together in an index. This will include self-reported propensity to share, and actual behavioral measures of different types of sharing (e.g., do they click through a button offering them the option to share, do they agree to send/message to friends), ensuring that we don't *actually* facilitate sharing of false information. Outcomes will be collected before and after treatment. 
Assigned: Molly
To do: 
  - [ ] Further refine and plug into the working [draft script](https://docs.google.com/spreadsheets/d/1hhWv_ZxVJA1xcfnK3URFWjN4awJjL1DvSc1HcSW9-sk/edit#gid=89947233)


- **Module on going viral for social good** (In development) This module addresses factors that make people more likely to share information. Because of the nature of viral campaigns, we will focus messaging on behaviors that are relevant to collective action problems for public health. See [tumblr](https://academic-survey-africa-covid19.tumblr.com/) for message considerations. After asking people about their preferences, we will ask people to take actions consistent with those preferences. 
Assigned: Molly to develop first mock-up, Leah to provide feedback
To do:
  - [ ] Develop and plug into the working [draft script](https://docs.google.com/spreadsheets/d/1hhWv_ZxVJA1xcfnK3URFWjN4awJjL1DvSc1HcSW9-sk/edit#gid=89947233)

**Comment by mollyow** [comment]
IRB Protocol #57430 on https://eprotocol.stanford.edu/
